#!/usr/bin/env python3
"""
Horizon Bridge — connects Horizon browser extension to Hermes agent.
Runs on localhost:8942. Start with: python3 bridge.py

Endpoints:
  GET  /api/health     — health check
  POST /api/query      — forward query to Hermes, return structured results
  GET  /api/briefing   — return today's briefing (generated by Hermes cron)
  POST /api/focus      — set today's focus in Hermes memory
  GET  /api/calendar   — return today's events
"""

import json
import os
import subprocess
import sys
import time
from http.server import HTTPServer, BaseHTTPRequestHandler
from pathlib import Path
from urllib.parse import urlparse

BRIDGE_DIR = Path.home() / ".horizon"
BRIEFING_FILE = BRIDGE_DIR / "briefing.json"
PORT = 8942


def call_hermes(prompt, timeout=30):
    """Call Hermes CLI with a single-shot query and return the response."""
    try:
        result = subprocess.run(
            ["hermes", "chat", "-q", prompt, "-Q"],
            capture_output=True,
            text=True,
            timeout=timeout,
            env={**os.environ, "HERMES_HOME": os.environ.get("HERMES_HOME", str(Path.home() / ".hermes"))},
        )
        if result.returncode == 0:
            return result.stdout.strip()
        return None
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return None


def load_briefing():
    """Load the latest briefing from disk."""
    if BRIEFING_FILE.exists():
        try:
            return json.loads(BRIEFING_FILE.read_text())
        except (json.JSONDecodeError, OSError):
            pass
    return None


def save_focus(text):
    """Save focus to a local file that Hermes cron can pick up."""
    BRIDGE_DIR.mkdir(parents=True, exist_ok=True)
    focus_file = BRIDGE_DIR / "focus.json"
    focus_file.write_text(json.dumps({"focus": text, "timestamp": time.time()}))


class BridgeHandler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        pass  # quiet

    def _send_json(self, data, status=200):
        body = json.dumps(data).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _read_body(self):
        length = int(self.headers.get("Content-Length", 0))
        if length:
            return json.loads(self.rfile.read(length))
        return {}

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_GET(self):
        path = urlparse(self.path).path

        if path == "/api/health":
            self._send_json({"status": "ok", "hermes": "connected"})

        elif path == "/api/briefing":
            briefing = load_briefing()
            if briefing:
                self._send_json(briefing)
            else:
                self._send_json({"available": False}, status=404)

        elif path == "/api/calendar":
            response = call_hermes(
                "List my calendar events for today. Return as JSON array with fields: time, title, location. Be concise.",
                timeout=15,
            )
            if response:
                try:
                    events = json.loads(response)
                    self._send_json({"events": events})
                except json.JSONDecodeError:
                    self._send_json({"events": [], "raw": response[:200]})
            else:
                self._send_json({"events": []})

        else:
            self._send_json({"error": "not found"}, status=404)

    def do_POST(self):
        path = urlparse(self.path).path
        body = self._read_body()

        if path == "/api/query":
            query = body.get("query", "")
            if not query:
                self._send_json({"results": []}, status=400)
                return

            response = call_hermes(
                f"Answer this query concisely as a JSON array of results. Each result has: title, detail, url (optional), action (optional). "
                f"Use your memory, calendar, email, and file system to find relevant information. "
                f"Query: {query}",
                timeout=20,
            )
            if response:
                try:
                    results = json.loads(response)
                    self._send_json({"results": results if isinstance(results, list) else [results]})
                except json.JSONDecodeError:
                    self._send_json({
                        "results": [{"title": "Hermes", "detail": response[:300]}]
                    })
            else:
                self._send_json({"results": []})

        elif path == "/api/focus":
            focus = body.get("focus", "")
            if focus:
                save_focus(focus)
                # Also try to save to Hermes memory
                call_hermes(
                    f"Save this to memory: my main focus for today is '{focus}'",
                    timeout=10,
                )
                self._send_json({"saved": True})
            else:
                self._send_json({"saved": False}, status=400)

        else:
            self._send_json({"error": "not found"}, status=404)


def main():
    BRIDGE_DIR.mkdir(parents=True, exist_ok=True)
    server = HTTPServer(("127.0.0.1", PORT), BridgeHandler)
    print(f"🌅 Horizon Bridge running on http://localhost:{PORT}")
    print(f"   Briefing: http://localhost:{PORT}/api/briefing")
    print(f"   Query:    POST http://localhost:{PORT}/api/query")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down.")
        server.shutdown()


if __name__ == "__main__":
    main()