#!/usr/bin/env python3
"""
Horizon Bridge — connects Horizon browser extension to Hermes agent.
Runs on localhost:8942. Start with: python3 bridge.py

Endpoints:
  GET  /api/health     — health check
  POST /api/query      — forward query to Hermes, return structured results
  GET  /api/briefing   — return today's briefing (generated by Hermes cron)
  POST /api/focus      — set today's focus in Hermes memory
  GET  /api/calendar   — return today's events
"""

import json
import os
import subprocess
import sys
import time
from http.server import HTTPServer, BaseHTTPRequestHandler
from pathlib import Path
from urllib.parse import urlparse

BRIDGE_DIR = Path.home() / ".horizon"
BRIEFING_FILE = BRIDGE_DIR / "briefing.json"
PORT = 8942


def call_hermes(prompt, timeout=30):
    """Call Hermes CLI with a single-shot query and return the response."""
    try:
        result = subprocess.run(
            ["hermes", "chat", "-q", prompt, "-Q"],
            capture_output=True,
            text=True,
            timeout=timeout,
            env={**os.environ, "HERMES_HOME": os.environ.get("HERMES_HOME", str(Path.home() / ".hermes"))},
        )
        if result.returncode == 0:
            return result.stdout.strip()
        return None
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return None


def load_briefing():
    """Load the latest briefing from disk."""
    if BRIEFING_FILE.exists():
        try:
            return json.loads(BRIEFING_FILE.read_text())
        except (json.JSONDecodeError, OSError):
            pass
    return None


def save_focus(text):
    """Save focus to a local file that Hermes cron can pick up."""
    BRIDGE_DIR.mkdir(parents=True, exist_ok=True)
    focus_file = BRIDGE_DIR / "focus.json"
    focus_file.write_text(json.dumps({"focus": text, "timestamp": time.time()}))


def parse_hermes_json(text):
    """Extract JSON from Hermes output, handling markdown code blocks."""
    import re
    # Strip markdown code blocks
    text = re.sub(r'^```(?:json)?\s*\n', '', text.strip())
    text = re.sub(r'\n```\s*$', '', text.strip())
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        # Try to find JSON object in the text
        match = re.search(r'\{.*\}|\[.*\]', text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                pass
    return None


class BridgeHandler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        pass  # quiet

    def _send_json(self, data, status=200):
        body = json.dumps(data).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Content-Length", str(len(body)))
        try:
            self.end_headers()
            self.wfile.write(body)
        except (BrokenPipeError, ConnectionResetError):
            pass  # client disconnected, that's fine

    def _read_body(self):
        length = int(self.headers.get("Content-Length", 0))
        if length:
            return json.loads(self.rfile.read(length))
        return {}

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_GET(self):
        path = urlparse(self.path).path

        if path == "/api/health":
            self._send_json({"status": "ok", "hermes": "connected"})

        elif path == "/api/briefing":
            briefing = load_briefing()
            if briefing:
                self._send_json(briefing)
            else:
                self._send_json({"available": False}, status=404)

        elif path == "/api/calendar":
            response = call_hermes(
                "List my calendar events for today. Return as JSON array with fields: time, title, location. Be concise.",
                timeout=15,
            )
            if response:
                events = parse_hermes_json(response)
                if events:
                    self._send_json({"events": events if isinstance(events, list) else [events]})
                else:
                    self._send_json({"events": [], "raw": response[:200]})
            else:
                self._send_json({"events": []})

        else:
            self._send_json({"error": "not found"}, status=404)

    def do_POST(self):
        path = urlparse(self.path).path
        body = self._read_body()

        if path == "/api/query":
            query = body.get("query", "")
            if not query:
                self._send_json({"results": []}, status=400)
                return

            prompt = (
                "You are the command bar for Horizon, a new tab page. "
                "Answer this query by returning a JSON array of results. "
                "Each result object must have: title (short label), detail (one-line description). "
                "Optional fields: url (to open), action (one of: open_file, open_url, compose_email, view_calendar, search_web, copy_text). "
                "When the action is open_file, include file_path (absolute path). "
                "When the action is compose_email, include email_to and email_subject. "
                "When the action is copy_text, include copy_value. "
                "Use your memory, calendar, email, file system, and browser history to find relevant information. "
                "Be specific and actionable — the user wants to DO something, not just read. "
                "Prioritize actions the user can take with one click. "
                f"Query: {query}"
            )
            response = call_hermes(prompt, timeout=30)
            if response:
                results = parse_hermes_json(response)
                if results:
                    self._send_json({"results": results if isinstance(results, list) else [results]})
                else:
                    self._send_json({
                        "results": [{"title": "Hermes", "detail": response[:300]}]
                    })
            else:
                self._send_json({"results": []})

        elif path == "/api/focus":
            focus = body.get("focus", "")
            if focus:
                save_focus(focus)
                # Also try to save to Hermes memory
                call_hermes(
                    f"Save this to memory: my main focus for today is '{focus}'",
                    timeout=10,
                )
                self._send_json({"saved": True})
            else:
                self._send_json({"saved": False}, status=400)

        else:
            self._send_json({"error": "not found"}, status=404)


def main():
    BRIDGE_DIR.mkdir(parents=True, exist_ok=True)
    server = HTTPServer(("127.0.0.1", PORT), BridgeHandler)
    print(f"🌅 Horizon Bridge running on http://localhost:{PORT}")
    print(f"   Briefing: http://localhost:{PORT}/api/briefing")
    print(f"   Query:    POST http://localhost:{PORT}/api/query")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down.")
        server.shutdown()


if __name__ == "__main__":
    main()