#!/usr/bin/env python3
"""
Horizon Bridge — connects Horizon browser extension to Hermes agent.
Runs on localhost:8942. Start with: python3 bridge.py

Endpoints:
  GET  /api/health     — health check
  POST /api/query      — forward query to Hermes, return structured results
  GET  /api/briefing   — return today's briefing (generated by Hermes cron)
  POST /api/focus      — set today's focus in Hermes memory
  GET  /api/calendar   — return today's events
  GET  /api/notifications — return pending notifications
  POST /api/notifications/clear — clear all notifications
  GET  /api/plan       — return today's planner spine + week strip (deterministic, fast)
  POST /api/plan/refresh — refresh calendar cache + Hermes suggestions (async, slow)
  POST /api/plan/accept  — accept a suggestion, remove from cache, log to memory
"""

import json
import os
import re
import socket
import subprocess
import sys
import time
from datetime import date, datetime, timedelta
from http.server import HTTPServer, BaseHTTPRequestHandler
from pathlib import Path
from urllib.parse import urlparse

BRIDGE_DIR = Path.home() / ".horizon"
BRIEFING_FILE = BRIDGE_DIR / "briefing.json"
NOTIFICATIONS_FILE = BRIDGE_DIR / "notifications.json"
PLAN_CACHE_FILE = BRIDGE_DIR / "plan_cache.json"
PLAN_EVENTS_FILE = BRIDGE_DIR / "plan_events.json"
PORT = 8942
REFRESH_STALENESS_SECONDS = 1800  # 30 minutes
SUGGESTION_CACHE_SECONDS = 1800   # 30 minutes


def load_plan_events():
    """Load cached calendar events. Returns {date, events:[], week:{}} or safe default."""
    if PLAN_EVENTS_FILE.exists():
        try:
            data = json.loads(PLAN_EVENTS_FILE.read_text())
            if isinstance(data, dict) and "date" in data:
                return data
        except (json.JSONDecodeError, OSError):
            pass
    return {"date": "", "events": [], "week": {}}


def load_plan_cache():
    """Load cached Hermes suggestions. Returns {generated_at, suggestions:[]} or empty."""
    if PLAN_CACHE_FILE.exists():
        try:
            data = json.loads(PLAN_CACHE_FILE.read_text())
            if isinstance(data, dict) and "suggestions" in data:
                return data
        except (json.JSONDecodeError, OSError):
            pass
    return {"generated_at": 0, "suggestions": []}


def compute_week_load(week_events):
    """Compute DayLoad objects for Monday-Sunday of the current week."""
    today = date.today()
    monday = today - timedelta(days=today.weekday())
    days = []

    for i in range(7):
        d = monday + timedelta(days=i)
        key = d.isoformat()
        day_events = week_events.get(key, []) if isinstance(week_events, dict) else []
        hours = 0.0
        has_all_day = False

        for ev in day_events:
            t = (ev.get("time") or "").strip()
            end = (ev.get("end") or "").strip()
            if not t:
                has_all_day = True
                continue
            try:
                start_dt = datetime.strptime(f"{key} {t}", "%Y-%m-%d %H:%M")
                end_dt = datetime.strptime(f"{key} {end}", "%Y-%m-%d %H:%M") if end else start_dt + timedelta(hours=1)
                h = (end_dt - start_dt).total_seconds() / 3600
                if h > 0:
                    hours += h
            except ValueError:
                hours += 1.0  # unparseable → assume 1 hour

        hours = round(hours, 1)
        if hours == 0 and has_all_day:
            load = "light"
        elif hours == 0:
            load = "none"
        elif hours < 2:
            load = "light"
        elif hours <= 4:
            load = "moderate"
        else:
            load = "heavy"

        days.append({
            "day": d.strftime("%a"),
            "date": key,
            "load": load,
            "hours": hours,
        })

    return days


def build_spine(events, suggestions):
    """Merge events and suggestions into a sorted spine list. Returns (spine, overflow_count)."""
    items = []
    for ev in (events or []):
        items.append({**ev, "type": "event"})
    for sug in (suggestions or []):
        sug = dict(sug)
        sug.setdefault("type", "suggestion")
        if "slot" in sug and "time" not in sug:
            sug["time"] = sug["slot"]
        items.append(sug)

    def sort_key(item):
        t = (item.get("time") or item.get("slot") or "").strip()
        return ("1_" + t) if t else "0_"

    items.sort(key=sort_key)
    overflow = max(0, len(items) - 5)
    return items[:5], overflow


def load_notifications():
    """Load pending notifications."""
    if NOTIFICATIONS_FILE.exists():
        try:
            data = json.loads(NOTIFICATIONS_FILE.read_text())
            return data if isinstance(data, list) else []
        except (json.JSONDecodeError, OSError):
            pass
    return []


def save_notifications(notifications):
    """Save notifications to disk."""
    BRIDGE_DIR.mkdir(parents=True, exist_ok=True)
    NOTIFICATIONS_FILE.write_text(json.dumps(notifications, indent=2))


def call_hermes(prompt, timeout=30):
    """Call Hermes CLI with a single-shot query and return the response."""
    try:
        result = subprocess.run(
            ["hermes", "chat", "-q", prompt, "-Q"],
            capture_output=True,
            text=True,
            timeout=timeout,
            env={**os.environ, "HERMES_HOME": os.environ.get("HERMES_HOME", str(Path.home() / ".hermes"))},
        )
        if result.returncode == 0:
            return result.stdout.strip()
        return None
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return None


def load_briefing():
    """Load the latest briefing from disk."""
    if BRIEFING_FILE.exists():
        try:
            return json.loads(BRIEFING_FILE.read_text())
        except (json.JSONDecodeError, OSError):
            pass
    return None


def save_focus(text):
    """Save focus to a local file that Hermes cron can pick up."""
    BRIDGE_DIR.mkdir(parents=True, exist_ok=True)
    focus_file = BRIDGE_DIR / "focus.json"
    focus_file.write_text(json.dumps({"focus": text, "timestamp": time.time()}))


def parse_hermes_json(text):
    """Extract JSON from Hermes output, handling markdown code blocks."""
    import re
    # Strip markdown code blocks
    text = re.sub(r'^```(?:json)?\s*\n', '', text.strip())
    text = re.sub(r'\n```\s*$', '', text.strip())
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        # Try to find JSON object in the text
        match = re.search(r'\{.*\}|\[.*\]', text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                pass
    return None


class ReuseHTTPServer(HTTPServer):
    """HTTPServer with SO_REUSEADDR set before bind."""
    def server_bind(self):
        self.socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        super().server_bind()


class BridgeHandler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        pass  # quiet

    def _send_json(self, data, status=200):
        body = json.dumps(data).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Content-Length", str(len(body)))
        try:
            self.end_headers()
            self.wfile.write(body)
        except (BrokenPipeError, ConnectionResetError):
            pass  # client disconnected, that's fine

    def _read_body(self):
        length = int(self.headers.get("Content-Length", 0))
        if length:
            return json.loads(self.rfile.read(length))
        return {}

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_GET(self):
        path = urlparse(self.path).path

        if path == "/api/health":
            self._send_json({"status": "ok", "hermes": "connected"})

        elif path == "/api/briefing":
            briefing = load_briefing()
            if briefing:
                self._send_json(briefing)
            else:
                self._send_json({"available": False}, status=404)

        elif path == "/api/calendar":
            response = call_hermes(
                "List my calendar events for today. Return as JSON array with fields: time, title, location. Be concise.",
                timeout=15,
            )
            if response:
                events = parse_hermes_json(response)
                if events:
                    self._send_json({"events": events if isinstance(events, list) else [events]})
                else:
                    self._send_json({"events": [], "raw": response[:200]})
            else:
                self._send_json({"events": []})

        elif path == "/api/notifications":
            notifications = load_notifications()
            self._send_json({"notifications": notifications})

        elif path == "/api/plan":
            today_str = date.today().isoformat()
            plan_events = load_plan_events()

            # Use cached events only if date matches today
            if plan_events.get("date") != today_str:
                plan_events = {"date": "", "events": [], "week": {}}

            # Load suggestions, checking staleness
            cache = load_plan_cache()
            suggestions_fresh = False
            suggestions = []
            if (time.time() - cache.get("generated_at", 0)) < SUGGESTION_CACHE_SECONDS:
                suggestions_fresh = True
                suggestions = cache.get("suggestions", [])

            spine, overflow = build_spine(plan_events.get("events", []), suggestions)
            week = compute_week_load(plan_events.get("week", {}))

            self._send_json({
                "date": today_str,
                "spine": spine,
                "overflow": overflow,
                "week": week,
                "suggestions_fresh": suggestions_fresh,
            })

        else:
            self._send_json({"error": "not found"}, status=404)

    def do_POST(self):
        path = urlparse(self.path).path
        body = self._read_body()

        if path == "/api/query":
            query = body.get("query", "")
            if not query:
                self._send_json({"results": []}, status=400)
                return

            prompt = (
                "You are the command bar for Horizon, a new tab page. "
                "Answer this query by returning a JSON array of results. "
                "Each result object must have: title (short label), detail (one-line description). "
                "Optional fields: url (to open), action (one of: open_file, open_url, compose_email, view_calendar, search_web, copy_text). "
                "When the action is open_file, include file_path (absolute path). "
                "When the action is compose_email, include email_to and email_subject. "
                "When the action is copy_text, include copy_value. "
                "Use your memory, calendar, email, file system, and browser history to find relevant information. "
                "Be specific and actionable — the user wants to DO something, not just read. "
                "Prioritize actions the user can take with one click. "
                f"Query: {query}"
            )
            response = call_hermes(prompt, timeout=30)
            if response:
                results = parse_hermes_json(response)
                if results:
                    self._send_json({"results": results if isinstance(results, list) else [results]})
                else:
                    self._send_json({
                        "results": [{"title": "Hermes", "detail": response[:300]}]
                    })
            else:
                self._send_json({"results": []})

        elif path == "/api/focus":
            focus = body.get("focus", "")
            if focus:
                save_focus(focus)
                call_hermes(
                    f"Save this to memory: my main focus for today is '{focus}'",
                    timeout=10,
                )
                self._send_json({"saved": True})
            else:
                self._send_json({"saved": False}, status=400)

        elif path == "/api/notifications/clear":
            save_notifications([])
            self._send_json({"cleared": True})

        elif path == "/api/plan/refresh":
            todos = body.get("todos", [])
            today_str = date.today().isoformat()
            today_events = []
            week_data = {}

            # Step 1: Fetch calendar events via Hermes
            cal_response = call_hermes(
                "List my calendar events for the next 7 days. Respond with ONLY a JSON object, "
                "no prose, shaped exactly like: "
                '{"events": [{"date": "YYYY-MM-DD", "time": "HH:MM", "end": "HH:MM", "title": "..."}]}. '
                "Use 24-hour times. If an event is all-day, use \"time\": \"\". If you do not know the end time, omit \"end\".",
                timeout=25,
            )
            cal_data = parse_hermes_json(cal_response) if cal_response else None
            if cal_data and isinstance(cal_data, dict) and "events" in cal_data:
                for ev in cal_data["events"]:
                    if not isinstance(ev, dict):
                        continue
                    ev_date = ev.get("date", "")
                    title = ev.get("title", "")
                    if not isinstance(ev_date, str) or not isinstance(title, str):
                        continue
                    ev_time = ev.get("time", "")
                    ev_end = ev.get("end", "")
                    ev_obj = {"title": title, "time": ev_time}
                    if ev_end:
                        ev_obj["end"] = ev_end
                    if ev_date == today_str:
                        today_events.append(ev_obj)
                    week_data.setdefault(ev_date, []).append(ev_obj)

                PLAN_EVENTS_FILE.write_text(json.dumps({
                    "date": today_str,
                    "events": today_events,
                    "week": week_data,
                }, indent=2))

            # Step 2: If we have events and todos, get Hermes suggestions
            suggestions = []
            if today_events and todos and isinstance(todos, list) and len(todos) > 0:
                sug_response = call_hermes(
                    f"My calendar today: {json.dumps(today_events)}. "
                    f"My open tasks: {json.dumps(todos)}. "
                    "Suggest at most 2 tasks to schedule into free gaps today. Respond with ONLY a JSON array, "
                    'no prose, shaped exactly like: [{"task": "<exact task text from my list>", "slot": "HH:MM", "reason": "<under 8 words>"}]. '
                    "The task field must be copied verbatim from my task list. Only suggest slots in the future. "
                    "If nothing fits, respond with [].",
                    timeout=25,
                )
                sug_data = parse_hermes_json(sug_response) if sug_response else None
                if sug_data and isinstance(sug_data, list):
                    todo_set = set(todos)
                    for item in sug_data:
                        if not isinstance(item, dict):
                            continue
                        task = item.get("task", "")
                        slot = item.get("slot", "")
                        reason = item.get("reason", "")
                        if (isinstance(task, str) and task in todo_set
                                and isinstance(slot, str) and re.match(r'^\d{2}:\d{2}$', slot)
                                and isinstance(reason, str)):
                            suggestions.append({
                                "task": task,
                                "slot": slot,
                                "reason": reason,
                                "type": "suggestion",
                            })

            PLAN_CACHE_FILE.write_text(json.dumps({
                "generated_at": time.time(),
                "suggestions": suggestions,
            }, indent=2))

            self._send_json({"refreshed": True, "suggestions": len(suggestions)})

        elif path == "/api/plan/accept":
            task = body.get("task", "")
            slot = body.get("slot", "")
            if not isinstance(task, str) or not isinstance(slot, str) or not task or not slot:
                self._send_json({"error": "task and slot required"}, status=400)
                return

            # Remove matching suggestion from cache
            cache = load_plan_cache()
            old_len = len(cache.get("suggestions", []))
            cache["suggestions"] = [s for s in cache.get("suggestions", [])
                                   if s.get("task") != task]
            if len(cache["suggestions"]) != old_len:
                PLAN_CACHE_FILE.write_text(json.dumps(cache, indent=2))

            # Log to Hermes memory
            call_hermes(
                f"Save this to memory: I scheduled the task '{task}' for {slot} today via the Horizon planner.",
                timeout=10,
            )
            self._send_json({"accepted": True})

        else:
            self._send_json({"error": "not found"}, status=404)


def main():
    BRIDGE_DIR.mkdir(parents=True, exist_ok=True)
    server = ReuseHTTPServer(("127.0.0.1", PORT), BridgeHandler)
    print(f"🌅 Horizon Bridge running on http://localhost:{PORT}")
    print(f"   Briefing: http://localhost:{PORT}/api/briefing")
    print(f"   Query:    POST http://localhost:{PORT}/api/query")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down.")
        server.shutdown()


if __name__ == "__main__":
    main()